### ISSUE TITLE
基本情報をアップデートする

### ISSUE THREAD

**Issue by yamanoku** [yamanoku/yamanoku.github.io#999]
一児（娘）の父と3匹の猫の飼い主。
↓
一児（娘）の父と3匹の猫と1匹の犬の飼い主。

![写真：ゴールデン・レトリバーのジュン](https://user-images.githubusercontent.com/1996642/184627922-0808ec82-f708-4165-b041-f3f3b9c9ffcf.png)

**Comment by takanakahiko** [comment]
🎉
